### ISSUE TITLE
Unable to locate the index file for the generated BAM file

### ISSUE THREAD

**Issue by Lalitha611** [SdeBlank/NanoFG#24]
I've been attempting to run the demo data with the tool, but it seems to have difficulty locating the .bam.bai file. Upon inspecting the output directory, I noticed that while the BAM file is present, the .bam.bai file does not appear to have been generated. Could you assist in resolving this issue?

```
> (venv) (base) kamada@Lalithas-MacBook-Pro NanoFG % bash NanoFG.sh -f /Users/kamada/Downloads/NanoFG/demo/demo_fastqdir 

> Tue Jul  4 11:38:31 CEST 2023 	 Running on Lalithas-MacBook-Pro.local
> Tue Jul  4 11:38:31 CEST 2023 	 Mapping all reads using minimap2...
> [M::mm_idx_gen::47.781*0.86] collected minimizers
> [M::mm_idx_gen::77.760*0.90] sorted minimizers
> [M::main::77.763*0.90] loaded/built the index for 24 target sequence(s)
> [M::mm_mapopt_update::78.614*0.91] mid_occ = 601
> [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 24
> [M::mm_idx_stat::79.179*0.91] distinct minimizers: 99986389 (38.90% are singletons); average occurrences: 5.388; average spacing: 5.747; total length: 3095677412
> [M::worker_pipeline::99.418*0.90] mapped 7048 sequences
> [M::main] Version: 2.26-r1175
> [M::main] CMD: /opt/homebrew/bin/minimap2 -t 1 -x map-ont -a --MD /Volumes/Lalitha_SSD/hGRC37.fa /Users/kamada/Downloads/NanoFG/demo.merged.fastq
> [M::main] Real time: 99.687 sec; CPU: 89.681 sec; Peak RSS: 8.941 GB
> No selection parameter (-s) provided. Using all mapped reads
> Tue Jul  4 11:40:13 CEST 2023 	 SV calling...
> Tue Jul  4 11:40:13 2023 Busy with parsing bam file...
> [E::idx_find_and_load] Could not retrieve index file for '/Users/kamada/Downloads/NanoFG/demo.bam'
> The bam has no index file
> Tue Jul  4 11:40:13 CEST 2023 	 Removing insertions and all variants without a PASS filter...
> Tue Jul  4 11:40:13 CEST 2023 	 Extracting reads that support candidate fusion genes...
> Start: 2023-07-04 11:40:14.496966
> Traceback (most recent call last):
>   File "/Users/kamada/Downloads/NanoFG/scripts/FusionReadExtraction.py", line 176, in <module>
>     vcf_reader = pyvcf.Reader(open(args.vcf, 'r'))
>   File "/Users/kamada/Downloads/NanoFG/venv/lib/python3.10/site-packages/vcf/parser.py", line 300, in __init__
>     self._parse_metainfo()
>   File "/Users/kamada/Downloads/NanoFG/venv/lib/python3.10/site-packages/vcf/parser.py", line 317, in _parse_metainfo
>     line = next(self.reader)
> StopIteration
> !!! FUSION READ EXTRACTION NOT CORRECTLY COMPLETED... exiting
```

**Comment by SdeBlank** [comment]
Hey,

I pushed a change in minimap2 mapping that was leading to an error in building the index file, see if the index file is still not created when running NanoFG after pulling the latest changes
