### ISSUE TITLE
Errors with -b bam command

### ISSUE THREAD

**Issue by Lalitha611** [SdeBlank/NanoFG#25]
I attempted to use the tool with the BAM file generated from demo data and encountered an error. Could you kindly provide assistance with this?

```
(venv) (base) kamada@Lalithas-MacBook-Pro NanoFG % bash NanoFG.sh -b /Users/kamada/Downloads/NanoFG/demo.bam
Tue Jul  4 11:58:26 CEST 2023 	 Running on Lalithas-MacBook-Pro.local
### bam (-b) already provided. Skipping minimap2 mapping
### No selection parameter (-s) provided. Using all mapped reads
Tue Jul  4 11:58:26 CEST 2023 	 SV calling...
Tue Jul  4 11:58:26 2023 Busy with parsing bam file...
Process Process-1:
Traceback (most recent call last):
  File "/Users/kamada/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/kamada/anaconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kamada/Downloads/NanoFG/venv/lib/python3.10/site-packages/nanosv/utils/../utils/parse_bam.py", line 112, in parse_chr_bam
    for item in header["SQ"]:
NameError: name 'header' is not defined




^CTraceback (most recent call last):
  File "/Users/kamada/Downloads/NanoFG/venv/bin/nanosv", line 8, in <module>
    sys.exit(main())
  File "/Users/kamada/Downloads/NanoFG/venv/lib/python3.10/site-packages/nanosv/NanoSV.py", line 71, in main
    utils.parse_bam.parse_bam()
  File "/Users/kamada/Downloads/NanoFG/venv/lib/python3.10/site-packages/nanosv/utils/../utils/parse_bam.py", line 70, in parse_bam
    time.sleep(5)    # Give tasks a chance to put more data in
KeyboardInterrupt
```

Also, I also tried running the tool with my own bam file and encountered the error below:
```
(venv) (base) kamada@Lalithas-MacBook-Pro NanoFG % bash NanoFG.sh -b /Users/kamada/Downloads/NanoFG/demo/demo_bamdir/output.bam
Tue Jul  4 12:20:13 CEST 2023 	 Running on Lalithas-MacBook-Pro.local
### bam (-b) already provided. Skipping minimap2 mapping
### No selection parameter (-s) provided. Using all mapped reads
Tue Jul  4 12:20:13 CEST 2023 	 SV calling...
Tue Jul  4 12:20:14 2023 Busy with parsing bam file...
Process Process-1:
Traceback (most recent call last):
  File "/Users/kamada/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/kamada/anaconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kamada/Downloads/NanoFG/venv/lib/python3.10/site-packages/nanosv/utils/../utils/parse_bam.py", line 112, in parse_chr_bam
    for item in header["SQ"]:
NameError: name 'header' is not defined
^CTraceback (most recent call last):
  File "/Users/kamada/Downloads/NanoFG/venv/bin/nanosv", line 8, in <module>
    sys.exit(main())
  File "/Users/kamada/Downloads/NanoFG/venv/lib/python3.10/site-packages/nanosv/NanoSV.py", line 71, in main
    utils.parse_bam.parse_bam()
  File "/Users/kamada/Downloads/NanoFG/venv/lib/python3.10/site-packages/nanosv/utils/../utils/parse_bam.py", line 70, in parse_bam
    time.sleep(5)    # Give tasks a chance to put more data in
KeyboardInterrupt
```

The header of output.bam is:
```
(base) kamada@Lalithas-MacBook-Pro demo_bamdir % samtools view -H output.bam
@HD	VN:1.6	SO:coordinate
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr2	LN:243199373
@SQ	SN:chr3	LN:198022430
@SQ	SN:chr4	LN:191154276
@SQ	SN:chr5	LN:180915260
@SQ	SN:chr6	LN:171115067
@SQ	SN:chr7	LN:159138663
@SQ	SN:chrX	LN:155270560
@SQ	SN:chr8	LN:146364022
@SQ	SN:chr9	LN:141213431
@SQ	SN:chr10	LN:135534747
@SQ	SN:chr11	LN:135006516
@SQ	SN:chr12	LN:133851895
@SQ	SN:chr13	LN:115169878
@SQ	SN:chr14	LN:107349540
@SQ	SN:chr15	LN:102531392
@SQ	SN:chr16	LN:90354753
@SQ	SN:chr17	LN:81195210
@SQ	SN:chr18	LN:78077248
@SQ	SN:chr20	LN:63025520
@SQ	SN:chrY	LN:59373566
@SQ	SN:chr19	LN:59128983
@SQ	SN:chr22	LN:51304566
@SQ	SN:chr21	LN:48129895
@SQ	SN:chr6_ssto_hap7	LN:4928567
@SQ	SN:chr6_mcf_hap5	LN:4833398
@SQ	SN:chr6_cox_hap2	LN:4795371
@SQ	SN:chr6_mann_hap4	LN:4683263
@SQ	SN:chr6_apd_hap1	LN:4622290
@SQ	SN:chr6_qbl_hap6	LN:4611984
@SQ	SN:chr6_dbb_hap3	LN:4610396
@SQ	SN:chr17_ctg5_hap1	LN:1680828
@SQ	SN:chr4_ctg9_hap1	LN:590426
@SQ	SN:chr1_gl000192_random	LN:547496
@SQ	SN:chrUn_gl000225	LN:211173
@SQ	SN:chr4_gl000194_random	LN:191469
@SQ	SN:chr4_gl000193_random	LN:189789
@SQ	SN:chr9_gl000200_random	LN:187035
@SQ	SN:chrUn_gl000222	LN:186861
@SQ	SN:chrUn_gl000212	LN:186858
@SQ	SN:chr7_gl000195_random	LN:182896
@SQ	SN:chrUn_gl000223	LN:180455
@SQ	SN:chrUn_gl000224	LN:179693
@SQ	SN:chrUn_gl000219	LN:179198
@SQ	SN:chr17_gl000205_random	LN:174588
@SQ	SN:chrUn_gl000215	LN:172545
@SQ	SN:chrUn_gl000216	LN:172294
@SQ	SN:chrUn_gl000217	LN:172149
@SQ	SN:chr9_gl000199_random	LN:169874
@SQ	SN:chrUn_gl000211	LN:166566
@SQ	SN:chrUn_gl000213	LN:164239
@SQ	SN:chrUn_gl000220	LN:161802
@SQ	SN:chrUn_gl000218	LN:161147
@SQ	SN:chr19_gl000209_random	LN:159169
@SQ	SN:chrUn_gl000221	LN:155397
@SQ	SN:chrUn_gl000214	LN:137718
@SQ	SN:chrUn_gl000228	LN:129120
@SQ	SN:chrUn_gl000227	LN:128374
@SQ	SN:chr1_gl000191_random	LN:106433
@SQ	SN:chr19_gl000208_random	LN:92689
@SQ	SN:chr9_gl000198_random	LN:90085
@SQ	SN:chr17_gl000204_random	LN:81310
@SQ	SN:chrUn_gl000233	LN:45941
@SQ	SN:chrUn_gl000237	LN:45867
@SQ	SN:chrUn_gl000230	LN:43691
@SQ	SN:chrUn_gl000242	LN:43523
@SQ	SN:chrUn_gl000243	LN:43341
@SQ	SN:chrUn_gl000241	LN:42152
@SQ	SN:chrUn_gl000236	LN:41934
@SQ	SN:chrUn_gl000240	LN:41933
@SQ	SN:chr17_gl000206_random	LN:41001
@SQ	SN:chrUn_gl000232	LN:40652
@SQ	SN:chrUn_gl000234	LN:40531
@SQ	SN:chr11_gl000202_random	LN:40103
@SQ	SN:chrUn_gl000238	LN:39939
@SQ	SN:chrUn_gl000244	LN:39929
@SQ	SN:chrUn_gl000248	LN:39786
@SQ	SN:chr8_gl000196_random	LN:38914
@SQ	SN:chrUn_gl000249	LN:38502
@SQ	SN:chrUn_gl000246	LN:38154
@SQ	SN:chr17_gl000203_random	LN:37498
@SQ	SN:chr8_gl000197_random	LN:37175
@SQ	SN:chrUn_gl000245	LN:36651
@SQ	SN:chrUn_gl000247	LN:36422
@SQ	SN:chr9_gl000201_random	LN:36148
@SQ	SN:chrUn_gl000235	LN:34474
@SQ	SN:chrUn_gl000239	LN:33824
@SQ	SN:chr21_gl000210_random	LN:27682
@SQ	SN:chrUn_gl000231	LN:27386
@SQ	SN:chrUn_gl000229	LN:19913
@SQ	SN:chrM	LN:16571
@SQ	SN:chrUn_gl000226	LN:15008
@SQ	SN:chr18_gl000207_random	LN:4262
@PG	ID:aligner	PN:minimap2	VN:2.24-r1122
@PG	ID:basecaller	PN:guppy	VN:6.5.7+ca6d6af	CL:guppy_basecaller --input_path ./ --save_path ../results_newbasecalling --num_callers 64 --flowcell FLO-MIN106 --kit SQK-CS9109 --compress_fastq --align_ref /gpfs/project/dik09gax/nanopore_seq/hg19.fa --bam_out --index
@RG	ID:2eed4e4350523f2b62a858234c2335f032d35e00_2021-05-17_dna_r9.4.1_minion_384_d37a2ab9	SM:test_run	DT:2023-06-20T14:16:17.080919+02:00	DS:runid=2eed4e4350523f2b62a858234c2335f032d35e00 basecall_model=2021-05-17_dna_r9.4.1_minion_384_d37a2ab9	LB:REH-697_1-1000	PL:ONT	PM:MN43522	PU:FAW66019	al:REH-697_1-1000
@PG	ID:samtools	PN:samtools	PP:aligner	VN:1.7	CL:samtools reheader header.sam bam_runid_2eed4e4350523f2b62a858234c2335f032d35e00_0_0_sorted.bam
@PG	ID:samtools.1	PN:samtools	PP:basecaller	VN:1.7	CL:samtools reheader header.sam bam_runid_2eed4e4350523f2b62a858234c2335f032d35e00_0_0_sorted.bam
```

**Comment by SdeBlank** [comment]
Hey,

I am unsure if this the best fix possible, as the error occurs in the nanosv package, which I did not write. However, I forked it and changed something that for me seems to get through the "header" error. 

Download the following github and change the path in the paths.ini file and see if it works:
https://github.com/SdeBlank/nanosv
